# Generated by Django 5.2 on 2025-05-08 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_typesofhouse_supportingimages_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingimages',
            name='type_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.typesofhouse'),
        ),
        migrations.CreateModel(
            name='ConstructionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_stages', to='App1.typesofhouse')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('type_of_payment', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.constructionstage')),
            ],
        ),
    ]
