# Generated by Django 5.2 on 2025-05-08 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_supportingimages_type_house_constructionstage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionstage',
            name='house_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.typesofhouse'),
        ),
    ]
