# Generated by Django 5.2 on 2025-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_constructionstage_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionstage',
            name='sequence',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
