# Generated by Django 5.2 on 2025-05-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_constructionstage_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('location', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=50)),
            ],
        ),
    ]
