# Generated by Django 5.2 on 2025-05-12 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_design', models.BooleanField(default=True)),
                ('design_2D', models.ImageField(upload_to='designs/2d/')),
                ('design_3D', models.ImageField(upload_to='designs/3d/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='App1.clients')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='App1.project')),
            ],
        ),
        migrations.CreateModel(
            name='MinutesofMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('attended_by', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='Online', max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.project')),
            ],
        ),
    ]
