# Generated by Django 5.2 on 2025-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_design_minutesofmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='designed_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
