# Generated by Django 5.2 on 2025-06-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_alter_project_designed_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clients',
            name='document_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='document_type',
            field=models.CharField(blank=True, choices=[('AADHAR', 'Aadhar'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
    ]
