# Generated by Django 5.1.7 on 2025-06-11 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_remove_project_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructiondetail',
            old_name='completed_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='constructiondetail',
            name='type_of_payment',
        ),
        migrations.AddField(
            model_name='constructiondetail',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Project_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.project')),
            ],
        ),
    ]
