# Generated by Django 5.1.7 on 2025-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_rename_completed_date_constructiondetail_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
